### ISSUE TITLE
getUUIDString() errors

### ISSUE THREAD

**Issue by atwright147** [RamyElkest/libvirt-node#36]
Hey,

Is `getUUIDString()` working correctly? When I try to use it in the same way as I would use `getName()`, `getID()` or `getOSType()` I get the following error:

```
ReferenceError: buf is not defined
    at module.exports.getUUIDString (/vagrant/node_modules/libvirt-node/generated/libvirt-domain.js:870:66)
    at domains.forEach.domain (/vagrant/src/server/models/Domains.js:50:41)
    at Array.forEach (<anonymous>)
    at Object.allCompact (/vagrant/src/server/models/Domains.js:46:17)
    at compact (/vagrant/src/server/controllers/DomainsController.js:19:45)
    at Layer.handle [as handle_request] (/vagrant/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/vagrant/node_modules/express/lib/router/index.js:317:13)
    at /vagrant/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/vagrant/node_modules/express/lib/router/index.js:335:12)
    at next (/vagrant/node_modules/express/lib/router/index.js:275:10)
```

It seems to require a buffer (`buf`) to be passed in but I cannot figure out what to pass into that.

Here is a code example:

```js
const domains = LibvirtClient.listAllDomains(0);
const domainsWithInfo = [];

domains.forEach(domain => {
    const domainInfo = {};
    domainInfo['name'] = domain.getName();
    domainInfo['uuid'] = domain.getUUIDString();  // without this line, this loop works; with it is fails :(
    domainInfo['id'] = domain.getID();
    domainInfo['osType'] = domain.getOSType();

    domainsWithInfo.push(domainInfo);
});

return domainsWithInfo;
```

Cheers

**Comment by RamyElkest** [comment]
Hey @atwright147m yeah, that's a bug. I'll push a fix in the next couple of days if that's okay with you

**Comment by atwright147** [comment]
Superb, thank you :)

**Comment by atwright147** [comment]
Fixed by: https://github.com/RamyElkest/libvirt-node/pull/38

**Comment by atwright147** [comment]
I shouldn't have closed this without checking that it actually works.

But I have tried it out now it can confirm that it does work now :)

Thanks @RamyElkest
