### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by atwright147** [RamyElkest/libvirt-node#39]
An issue I am having now is that Libvirt is spitting out lovely useful messages into the terminal but I cannot seem to get them.

Terminal output after an error:

```
libvirt: Domain Config error : operation failed: domain 'created_from_post' already exists with uuid d6bd24d8-ff09-426d-ae23-e8c3cdb696e6
Error: virDomainDefineXML() failed
    at module.exports.defineXML (/vagrant/node_modules/libvirt-node/generated/libvirt-connect.js:708:28)
    at Object.create (/vagrant/src/server/models/Domains.js:67:38)
    at create (/vagrant/src/server/controllers/DomainsController.js:34:21)
    at Layer.handle [as handle_request] (/vagrant/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/vagrant/node_modules/express/lib/router/index.js:317:13)
    at /vagrant/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/vagrant/node_modules/express/lib/router/index.js:335:12)
    at next (/vagrant/node_modules/express/lib/router/index.js:275:10)
    at nocache (/vagrant/node_modules/nocache/index.js:8:5)
    at Layer.handle [as handle_request] (/vagrant/node_modules/express/lib/router/layer.js:95:5)
```

I can only get: `virDomainDefineXML() failed`, but would `Domain Config error : operation failed: domain 'created_from_post' already exists with uuid d6bd24d8-ff09-426d-ae23-e8c3cdb696e6` be way more useful to me.

Is there something I am doing wrong, or could you make a change to expose these messages?

**Comment by atwright147** [comment]
@RamyElkest do you have any thoughts on this?
